### ISSUE TITLE
`TypeId` downcast error in v0.1.31

### ISSUE THREAD

**Issue by michaelsproul** [est31/cargo-udeps#135]
When running cargo-udeps on [Lighthouse](https://github.com/sigp/lighthouse) it fails with the following error:

```
cargo +nightly-2022-08-11 udeps --tests --all-targets --release
thread 'main' panicked at 'Mismatch between definition and access: Could not downcast to TypeId { t: 11046744883169582909 }, need to downcast to TypeId { t: 1896031399542294508 }
', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.64.0/src/cargo/util/command_prelude.rs:736:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:189: udeps] Error 101
```

I've tried both a recent nightly (2022-08-11) and a previous one that we had pinned on CI (nightly-2022-05-20).

For now we'll downgrade to v0.1.30

**Comment by michaelsproul** [comment]
Here's a longer backtrace:

```
thread 'main' panicked at 'Mismatch between definition and access: Could not downcast to TypeId { t: 11046744883169582909 }, need to downcast to TypeId { t: 1896031399542294508 }
', /home/michael/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.64.0/src/cargo/util/command_prelude.rs:736:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: <clap::parser::matches::arg_matches::ArgMatches as cargo::util::command_prelude::ArgMatchesExt>::flag
   3: cargo::util::command_prelude::ArgMatchesExt::compile_options
   4: cargo_udeps::run
   5: cargo_udeps::main
```

**Comment by smoelius** [comment]
I also ran into this passing just `--tests`. The issue seems related to https://github.com/rust-lang/cargo/issues/10814.

Passing just `--all-targets` works for me though, though.

**Comment by est31** [comment]
Hmm yeah I think one has to set the value parser to bool for all bool flags, similar to 9a7a95e1fb03a1c180d55276c317546c675ba689 which fixed CI.
