### ISSUE TITLE
Panic when used with complex dependency graph

### ISSUE THREAD

**Issue by jonhoo** [est31/cargo-udeps#47]
To reproduce, check out [`noria`](https://github.com/mit-pdos/noria) (specifically https://github.com/mit-pdos/noria/commit/fb1da756d41b40fccf3c5d1266acbaaba586f0a6) and run `cargo udeps` in the root:
```
cargo udeps
    Blocking waiting for file lock on build directory
    Checking nix v0.16.1
    Checking noria v0.3.0 (/home/jon/dev/projects/noria/noria)
    Checking trawler-mysql v0.3.0 (/home/jon/dev/projects/noria/noria-benchmarks/lobsters)
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc_typeck/check/mod.rs:840:14
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: rustc_driver::report_ice
  11: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/698fcd38fa9548e64a2092ff48c9d15ceb57d40c/src/liballoc/boxed.rs:1029
  12: proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}
             at /rustc/698fcd38fa9548e64a2092ff48c9d15ceb57d40c/src/libproc_macro/bridge/client.rs:305
  13: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
  14: rust_begin_unwind
             at src/libstd/panicking.rs:380
  15: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  16: core::panicking::panic
             at src/libcore/panicking.rs:52
  17: rustc_typeck::check::has_typeck_tables
  18: rustc::ty::query::__query_compute::has_typeck_tables
  19: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors for rustc::ty::query::queries::has_typeck_tables>::compute
  20: rustc::dep_graph::graph::DepGraph::with_task_impl
  21: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt>::get_query
  22: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_ty
  23: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  24: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_item
  25: <rustc_save_analysis::dump_visitor::DumpVisitor as syntax::visit::Visitor>::visit_mod
  26: rustc::dep_graph::graph::DepGraph::with_ignore
  27: rustc::ty::context::tls::enter_global
  28: rustc_interface::interface::run_compiler_in_existing_thread_pool
  29: scoped_tls::ScopedKey<T>::set
  30: syntax::with_globals
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.42.0-nightly (698fcd38f 2020-01-26) running on x86_64-unknown-linux-gnu

note: compiler flags: -Z save-analysis -C debuginfo=2 -C incremental -C target-cpu=native --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [has_typeck_tables] processing `<controller::Controller<A> as tower_service::Service<controller::ControllerRequest>>::Future::{{opaque}}#0`
end of query stack
error: could not compile `noria`.
```
Note that this also happens if you run it in a particular sub-crate's root (like `noria/`).

**Comment by est31** [comment]
@jonhoo it seems like a problem with save analysis generation, which cargo-udeps uses. If that's the case it would be an upstream bug. Do you have the same issue if you use rls with the repo?

**Comment by jonhoo** [comment]
Seems pretty likely it is an upstream bug, but I'm not sure how to replicate it without `cargo-udeps`. Running `rls` in the root of the repository does not produce the error, if that's what you meant?

**Comment by est31** [comment]
`cargo udeps -v` prints the rustc commands invoked. All we do different from a `cargo check` run is that we add `-Z save-analysis` (more or less). I'd file an upstream bug next.

**Comment by jonhoo** [comment]
:+1: Filed https://github.com/rust-lang/rust/issues/68621

**Comment by est31** [comment]
>  Running rls in the root of the repository does not produce the error, if that's what you meant?

IIRC that does nothing but only starts the language service, waiting for commands to be specified in json. both cargo udeps and rls rely on save analysis info from rustc, but it is only being emitted when you actually let rls compile the project. Trying to use vscode+rls on master gives me an error that tokio-tower can't be compiled. Not sure how to debug that.

I can reproduce the issue on noria's master, but not the linked commit as it gives me:

```
 Updating git repository `https://github.com/jonhoo/memcached-rs.git`
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to load source for a dependency on `memcached-rs`

Caused by:
  Unable to update https://github.com/jonhoo/memcached-rs.git?branch=bump-deps#86170708

Caused by:
  revspec '86170708ab2b24c2eb5dbb16d5a3dd61337c18ea' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by jonhoo** [comment]
Yeah, that commit no longer compiles (the ecosystem moved quickly :sweat_smile:). `master` should be fine.

**Comment by jonhoo** [comment]
Looks like the upstream issue has been fixed in https://github.com/rust-lang/rust/pull/68744. I guess now we just have to wait and see if that makes it possible to run `cargo udeps` on noria itself :p

**Comment by est31** [comment]
Cargo udeps + latest rustc nightly works with noria master. Closing. Thanks for your report.
