### ISSUE TITLE
panic and hang when using --all-targets

### ISSUE THREAD

**Issue by oconnor663** [est31/cargo-udeps#6]
```
git clone https://github.com/oconnor663/shared_child.rs
cd shared_child.rs
cargo +nightly udeps --all-targets
```

In the build output of the last command, I see this panic:

    thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21

The build then hangs until I kill it with Ctrl-C.

This issue seems to repro in all the projects I've tried. Everything works fine if I don't use `--all-targets` though.

**Comment by matthiaskrgr** [comment]
I think I get the same when checking clippy:

````
   Compiling clippy v0.0.212 (/home/matthias/vcs/github/rust-clippy)
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.35/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::panicking::panic
             at src/libcore/panicking.rs:49
  11: <cargo_udeps::Exec as cargo::core::compiler::Executor>::exec
  12: <F as cargo::core::compiler::job::FnBox<A,R>>::call_box
  13: <F as cargo::core::compiler::job::FnBox<A,R>>::call_box
  14: <F as cargo::core::compiler::job::FnBox<A,R>>::call_box
  15: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
````

**Comment by jstoneham** [comment]
Same here using `cargo udeps --tests` on our projects.

**Comment by est31** [comment]
So I had a look. It seems that cargo can also sometimes omit the `crate-type` param. I've pushed a commit to assume a default here: 0417dc10405a12b8bf28b1a1677e36f8f31cbe65

I've verified that it fixes the original report by @oconnor663 . @matthiaskrgr @jstoneham if it still occurs for you, please file separate issues.

**Comment by jstoneham** [comment]
Is there a new release, or is there a way to install a non-release build to try it?

**Comment by jstoneham** [comment]
I figured it out. Seems to work for me. Thanks.
